name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn build
